import "./globals.css"
import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import { Header } from "@/ui/header"
import { Footer } from "@/ui/footer"
import { Sidebar } from "@/ui/sidebar"
import { Cart } from "@/ui/cart"

const montserrat = Montserrat({
	weight: ["400", "600", "700"],
	subsets: ["latin"],
	display: "swap",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="pl">
			<body className={montserrat.className}>
				<Header />
				<div className="flex overflow-hidden">
					<Sidebar />
					<div className={`relative z-10 h-screen overflow-auto border-l border-lines pt-[123px] `}>
						<div className="bg-workSpace p-5">{children}</div>
						<Footer />
					</div>
				</div>
				<Cart />
			</body>
		</html>
	)
}
