import "./globals.css"
import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import { Header } from "@/ui/Header"
import { Footer } from "@/ui/Footer"
import { Sidebar } from "@/ui/Sidebar"
import { CartSidebar, CartSimpleView, CartSummary } from "@/ui/Cart"

const montserrat = Montserrat({
	weight: ["400", "600", "700"],
	subsets: ["latin"],
	display: "swap",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="pl">
			<body className={montserrat.className}>
				<Header />
				<div className="flex overflow-hidden">
					<Sidebar />
					<div
						className={`relative z-10 h-screen overflow-auto border-l border-lines bg-workSpace pt-[139px]`}
					>
						<div className="bg-workSpace p-5">{children}</div>
						<Footer />
					</div>
				</div>
				{/* //TODO: przygotowane do RSC */}
				<CartSidebar simpleView={<CartSimpleView />} summary={<CartSummary />} />{" "}
			</body>
		</html>
	)
}
